[package]
name = "verify-student-gl-setup"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitlab = "0.1600.1"
serde = "1.0.152"

